### PR TITLE
Ghostscript for pdf conversion

### PR DESCRIPTION
**Pull request by nunomsfranco**
Added ghostscript for pdf conversion in response to the issues with some pdfs and ocrmypdf.
Some pdf do not convert properly to pdfa with ghostscript, running ocrmypdf with skip-text option fixes that, also files that were having issues with ocrmypdf after passing with ghostscript no longer have issues.
In some very rare situations, the skip-text still does not set the file to pdfa, so force-ocr is done as a last resort, if the file still is not pdfa then an error is raised indicating that it was not possible to convert the file.

### CODE REVIEW

**Review by JoseLucioNascimento — APPROVED** [review]
Approved.
But upon seeing some of these strings I was wondering if we can't find a way to move them to another file or something of sorts so that we can reuse them if needed or to centralize them elsewhere for easier access and such (Just a suggestion for the future if it proves to be useful)

**Comment by nunomsfranco** [comment]
That is a good idea, yes it's possible to add it in the config.yml for a more centralized and easier access

**Review by JoseLucioNascimento — APPROVED** [review]

**Comment by numsu** [comment]
What was the reason we excluded ghostscript last time? Did it convert badly or was ocrmypdf simply better? Now it uses ghostscript as option 1, does the output quality decrease? Does it show down or speed up? Any other noticeable changes to the pdf end result?

**Comment by nunomsfranco** [comment]
The reason we rejected ghostscript last time was as a substitute for the libreoffice, at the time it indeed decreased the quality of the file and it was slower as well.
I've tested now with only pdf conversion and the quality is the same as the original, the speed its the same as the ocr on skip-text.
That file you sent to me with the 2900 pages converted in ~2 min just ghostscript.
There is a possibility that the end result may be different if the ghostscript can't find a similar font as the original file, but even in those situations, the end result is very similar. I will send you a zip with the converted files if you want.

**Comment by numsu** [comment]
Thanks, no need to send them. I trust your judgement :)

**Review by numsu — APPROVED** [review]

**Pull request merged**
